Repository Unity-Technologies/com.unity.multiplayer.docs, pull requests merged in 2021-09, with the labels that each got.

#280 tweaking tables for mobile view
  docs/getting-started/about-mlapi.md
  versioned_docs/version-0.1.0/getting-started/about-mlapi.md
Labels: documentation, update, IN JIRA

#269 Mttdoc309 object pool updates
  docs/advanced-topics/object-pooling.md
  docs/getting-started/maxnumberplayers.md
  docs/reference/glossary/network-latency-management.md
  sidebars.js
  versioned_docs/version-0.1.0/reference/glossary/network-latency-management.md
Labels: documentation, IN JIRA

#254 feat: Add doc for network time and ticks
  docs/advanced-topics/network-update-loop-system/index.md
  docs/advanced-topics/networktime-ticks.md
  docusaurus.config.js
  package.json
  sidebars.js
  versioned_docs/version-0.1.0/advanced-topics/network-update-loop-system/index.md
  yarn.lock
Labels: documentation, new content, IN JIRA

#284 Update installation.md
  docs/migration/installation.md
  versioned_docs/version-0.1.0/migration/installation.md
Labels: documentation, type:feedback, IN JIRA

#292 New Video content from Dapper #MTTDOC-332
  docs/learn/dapper/dapper-video.md
  docs/learn/dapper/variable-permissions.md
  docs/tutorials/local_iteration_series/local-Iteration-testing-multiplayer-games-locally.md
  sidebars.js
  versioned_docs/version-0.1.0/learn/dapper/dapper-video.md
  versioned_docs/version-0.1.0/learn/dapper/variable-permissions.md
  versioned_sidebars/version-0.1.0-sidebars.json
Labels: documentation, update, IN JIRA
