Repository Unity-Technologies/com.unity.multiplayer.docs, pull requests merged in 2021-03, with the labels that each got.

#59 MTTDOC-115 Update settings for going public
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE.md
  docs/license.md
Labels: type:feature, update

#65 Pull content from #60 sandbox to master branch
  docs/components/networkanimator.md
  docs/components/networkmanager.md
  docs/components/networknavmeshagent.md
  docs/components/networktransform.md
  docs/core-components/core-components.md
  sidebars.js
Labels: documentation, new content

#73 Adding learn material from corrupt branches 46 and 49
  .gitignore
  docs/learn/lagandpacketloss.md
  docs/learn/listenserverhostarchitecture.md
  docs/learn/multiplayergamearhitectureintroduction.md
  docs/reference/glossary/high-level-terminology.md
  docs/reference/glossary/network-latency-management.md
  docs/reference/glossary/network-terms.md
  docs/reference/glossary/network-topologies.md
  docs/reference/glossary/prioritization.md
  docs/reference/glossary/relevancy.md
  docs/template.md
  sidebars.js
  src/ImageSwitcher.js
  src/css/unity-custom.scss
  static/img/client-hosted.jpg
  static/img/client-hosted.png
  static/img/data-relay-dark.png
  static/img/data-relay-light.png
  static/img/data-relay.jpg
  static/img/ded_server.jpg
  static/img/ded_server.png
  static/img/peer2peer1.png
  static/img/peer2peer_1.jpg
  static/img/ping-animation-dark.gif
  static/img/ping-animation-light.gif
  static/img/ping-animation.gif
  static/img/rpm_update_rates-dark.png
  static/img/rpm_update_rates-light.png
  static/img/tick_rate.png
  static/img/update-rates-dark.png
  static/img/update-rates-light.png
  static/img/update-rates.png
Labels: documentation, new content

#77 Adding in RPC/Netvar educational stuff
  docs/learn/index.md
  docs/learn/rpcnetvarexamples.md
  docs/learn/rpcvnetvar.md
  sidebars.js
  static/img/01_imp_not_appearing_dead.png
Labels: documentation, new content

#79 updating files for the two broken branches 27 and 17( messaging and serialization)
  docs/advanced-topics/message-system/clientrpc.md
  docs/advanced-topics/message-system/cross-compatibility.md
  docs/advanced-topics/message-system/deprecation-of-return-values.md
  docs/advanced-topics/message-system/execution-table.md
  docs/advanced-topics/message-system/reliabilty.md
  docs/advanced-topics/message-system/rpc-params.md
  docs/advanced-topics/message-system/serialization.md
  docs/advanced-topics/message-system/serverrpc.md
  docs/advanced-topics/messaging-system.md
  docs/advanced-topics/serialization/cprimatives.md
  docs/advanced-topics/serialization/enum-types.md
  docs/advanced-topics/serialization/inetworkserializable-bitserializer.md
  docs/advanced-topics/serialization/serialization-intro.md
  docs/advanced-topics/serialization/serializationstatic-arrays.md
  docs/advanced-topics/serialization/unity-primatives.md
  sidebars.js
Labels: documentation, new content

#75 Feature/mlapi upgrade guide
  docs/migration/installation.md
  docs/migration/migratingfrommlapi.md
  docs/migration/migratingtomlapi.md
  docs/tutorials/helloworldintro.md
  sidebars.js
Labels: documentation, new content

#93 Update networkvariable.md as per Feedback for /docs/mlapi-basics/networkvariable.md #92
  docs/mlapi-basics/networkvariable.md
Labels: documentation, update

#100 Update installation.md adding warning for install path
  docs/migration/installation.md
Labels: documentation, update

#94 Site: Onetrust and prism light/dark
  .gitignore
  README.md
  docs/migration/installation.md
  docusaurus.config.js
  package-lock.json
  package.json
  src/theme/CodeBlock/index.js
  src/theme/CodeBlock/styles.module.css
  yarn.lock
Labels: documentation, type:feature

#107 Update migratingtomlapi.md
  docs/migration/migratingtomlapi.md
Labels: documentation, type:bug

#110 Added point to download Git
  docs/migration/installation.md
Labels: documentation, update

#109 Adding-dapperdino-tutorialvideo
  docs/learn/dapper-video.md
  docs/template.md
  docusaurus.config.js
  sidebars.js
  src/css/unity-custom.scss
Labels: documentation, new content

#114 Updates to ways to synchronize
  docs/advanced-topics/ways-to-synchronize.md
Labels: documentation

#117 Mttdoc-135 Image formats, collapse sidebar, landing update
  docs/migration/migratingtomlapi.md
  docs/template.md
  docusaurus.config.js
  src/css/unity-custom.scss
  src/pages/index.js
  src/pages/styles.module.css
  src/theme/DocItem/index.js
  src/theme/DocItem/styles.module.css
  src/theme/Footer/index.js
  src/theme/Footer/styles.module.css
  static/img/hero-blog.jpg
  templates/markdown.md
Labels: documentation, type:feature

#121 Update networkmanager.md
  docs/components/networkmanager.md
Labels: documentation, update

#122 Adding latest dapper video
  docs/learn/dapper-video.md
Labels: documentation, new content

#125 MTTDOC-142 - MLAPI install patch URL
  docs/migration/installation.md
Labels: documentation, update
