Repository Unity-Technologies/com.unity.multiplayer.docs, pull requests merged in 2021-05, with the labels that each got.

#175 update: v1.0.0 object pooling documentation
  docs/advanced-topics/object-pooling.md
Labels: documentation, update

#173 Typo change
  versioned_docs/version-0.1.0/getting-started/about-mlapi.md
Labels: documentation

#176 updates - Multiple updates for user feedback
  community/license.md
  community/template.md
  docs/advanced-topics/serialization/inetworkserializable.md
  docs/getting-started/about-mlapi.md
  docs/getting-started/connection-approval.md
  docs/learn/bitesize-introduction.md
  docs/learn/bitesize-spaceshooter.md
  docs/learn/faq.md
  docs/migration/migratingfrommlapi.md
  docs/mlapi-basics/object-spawning.md
  docusaurus.config.js
  reference/contribute.md
  sidebars.js
  sidebarsTransport.js
  src/pages/index.js
  transport/connection-state-machine.md
  transport/event-consumption.md
  transport/index.md
  transport/install.md
  transport/pipelines-usage.md
  transport/samples/clientbehaviour.cs.md
  transport/samples/jobifiedclientbehaviour.cs.md
  transport/samples/jobifiedserverbehaviour.cs.md
  transport/samples/serverbehaviour.cs.md
  transport/update-flow.md
  transport/workflow-client-server-jobs.md
  transport/workflow-client-server.md
  versioned_docs/version-0.1.0/advanced-topics/serialization/inetworkserializable.md
  versioned_docs/version-0.1.0/getting-started/connection-approval.md
  versioned_docs/version-0.1.0/learn/bitesize-introduction.md
  versioned_docs/version-0.1.0/learn/faq.md
  versioned_docs/version-0.1.0/migration/migratingfrommlapi.md
  versioned_docs/version-0.1.0/transport/connection-state-machine.md
  versioned_docs/version-0.1.0/transport/event-consumption.md
  versioned_docs/version-0.1.0/transport/index.md
  versioned_docs/version-0.1.0/transport/install.md
  versioned_docs/version-0.1.0/transport/pipelines-usage.md
  versioned_docs/version-0.1.0/transport/samples/clientbehaviour.cs.md
  versioned_docs/version-0.1.0/transport/samples/jobifiedclientbehaviour.cs.md
  versioned_docs/version-0.1.0/transport/samples/jobifiedserverbehaviour.cs.md
  versioned_docs/version-0.1.0/transport/samples/serverbehaviour.cs.md
  versioned_docs/version-0.1.0/transport/update-flow.md
  versioned_docs/version-0.1.0/transport/workflow-client-server-jobs.md
  versioned_docs/version-0.1.0/transport/workflow-client-server.md
  versioned_sidebars/version-0.1.0-sidebars.json
Labels: documentation, type:feedback, update

#181 Update messaging-system.md
  docs/advanced-topics/message-system/about-rpc.md
  docs/advanced-topics/message-system/custom-messages.md
  docs/advanced-topics/messaging-system.md
  sidebars.js
  versioned_docs/version-0.1.0/advanced-topics/message-system/about-rpc.md
  versioned_docs/version-0.1.0/advanced-topics/message-system/custom-messages.md
  versioned_docs/version-0.1.0/advanced-topics/messaging-system.md
  versioned_sidebars/version-0.1.0-sidebars.json
Labels: documentation, update

#186 update: Install updates for 0.1.0
  docs/migration/installation.md
  static/img/install/develop-scene.png
  static/img/install/install-0-1-0-2021-name.png
  static/img/install/install-0-1-0-2021.png
  static/img/install/install-0-1-0-git.png
  static/img/install/install-git.png
  static/img/install/install-name.png
  static/img/install/install-unity-registry.png
  versioned_docs/version-0.1.0/migration/installation.md
Labels: documentation, update

#180 update: Close detail ( t ) mtt documentation windows and debug.log doesnt show in cmd
  docs/tutorials/goldenpath.md
  versioned_docs/version-0.1.0/tutorials/goldenpath.md
Labels: documentation, update

#192 updating text to reflect user comment on accuracy
  docs/mlapi-basics/object-spawning.md
  versioned_docs/version-0.1.0/mlapi-basics/object-spawning.md
Labels: IN JIRA, documentation, update

#191 Update bitesize-introduction.md
  docs/learn/bitesize-introduction.md
  versioned_docs/version-0.1.0/learn/bitesize-introduction.md
Labels: documentation, type:feedback, update

#187 Mttdoc 236 networking basics clientside interpolation and buffering
  docs/learn/clientside-interpolation.md
  docs/reference/glossary/network-latency-management.md
  sidebars.js
  versioned_docs/version-0.1.0/learn/clientside-interpolation.md
  versioned_docs/version-0.1.0/reference/glossary/network-latency-management.md
  versioned_sidebars/version-0.1.0-sidebars.json
Labels: documentation, update

#193 Boss Room 0.2.0 changelog
  blog/2021-05-19-boss-room-0-2-0.md
  docs/learn/listenserverhostarchitecture.md
  docs/learn/multiplayergamearhitectureintroduction.md
  docusaurus.config.js
  releases/index.md
  releases/samples/release-0-1-0.md
  releases/samples/release-0-2-0.md
  sidebars.js
  sidebarsReleases.js
  src/theme/DocVersionSuggestions/index.js
  transport_versioned_docs/version-0.8.0/install.md
  transport_versioned_docs/version-0.9.0/install.md
  versioned_docs/version-0.1.0/learn/listenserverhostarchitecture.md
  versioned_docs/version-0.1.0/learn/multiplayergamearhitectureintroduction.md
  versioned_sidebars/version-0.1.0-sidebars.json
  yarn.lock
Labels: documentation, new content

#188 [MTTSA-100] bitesize installation
  docs/learn/bitesize-introduction.md
  static/img/bitesize/bitesize-download.png
  static/img/bitesize/bitesize-download.xcf
Labels: documentation, update
